#:kivy 1.10.1

<Tir>:
    size: 5, 15
    canvas:
        Ellipse:
            pos: self.pos
            size: self.size

<Eleve>:

    size : 30, 10
    canvas:
        Ellipse:
            segments: 3
            pos: self.pos
            size: self.size



<ValidationGame>:

    tir: tir
    eleve: eleve

    Label:
        font_size: 20
        right: root.right - 5
        top: root.top - 3
        text: "Score :"

    Tir:
        id: tir
        center: self.parent.center